server:
  port: 8780
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-addService:
      path: /api-addService/**
      serviceId: add-service